services:
  - type: web
    name: boardmaster-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: boardmaster-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
        
databases:
  - name: boardmaster-db
    databaseName: boardmaster
    user: boardmaster
    region: oregon
    plan: free
